# yaml-language-server: $schema=./labels-schema.json

labels:
  - name: "Bug"
    description: "Something isn't working correctly"
    color: "d73a4a"
  - name: "Duplicate"
    description: "This issue or pull request already exists"
    color: "cfd3d7"
  - name: "Feature"
    description: "New feature or request"
    color: "a2eeef"
  - name: "Development"
    description: "Development related issue or pull request"
    color: "0e8a16"
  - name: "Documentation"
    description: "Improvements or additions to documentation"
    color: "0075ca"
  - name: "Enhancement"
    description: "Enhancement to existing functionality"
    color: "a2eeef"
  - name: "CI/CD"
    description: "Continuous Integration and Continuous Delivery related issue or pull request"
    color: "5319e7"
  - name: "Locales"
    description: "Localization and internationalization related issue or pull request"
    color: "f9d0c4"
  - name: "Breaking Change"
    description: "This change will cause existing functionality to not work as expected"
    color: "e11d21"
  - name: "Refactor"
    description: "Code change that neither fixes a bug nor adds a feature"
    color: "cfd3d7"

  - name: "packages/backend"
    description: "Label for related to backend package"
    color: "f9d0c4"
  - name: "packages/backend:test"
    description: "Label for related to backend package test"
    color: "f9d0c4"
  - name: "packages/frontend"
    description: "Label for related to frontend package"
    color: "f9d0c4"
  - name: "packages/frontend:test"
    description: "Label for related to frontend package test"
    color: "f9d0c4"
  - name: "packages/sw"
    description: "Label for related to sw package"
    color: "f9d0c4"
  - name: "packages/cherrypick-js"
    description: "Label for related to cherrypick-js package"
    color: "f9d0c4"
  - name: "packages/cherrypick-js:test"
    description: "Label for related to cherrypick-js package test"
    color: "f9d0c4"


