import type * as Account from "./entities/account";
import type * as Activity from "./entities/activity";
import type * as Announcement from "./entities/announcement";
import type * as Application from "./entities/application";
import type * as AsyncAttachment from "./entities/async_attachment";
import type * as Attachment from "./entities/attachment";
import type * as Card from "./entities/card";
import type * as Context from "./entities/context";
import type * as Conversation from "./entities/conversation";
import type * as Emoji from "./entities/emoji";
import type * as FeaturedTag from "./entities/featured_tag";
import type * as Field from "./entities/field";
import type * as Filter from "./entities/filter";
import type * as History from "./entities/history";
import type * as IdentityProof from "./entities/identity_proof";
import type * as Instance from "./entities/instance";
import type * as List from "./entities/list";
import type * as Marker from "./entities/marker";
import type * as Mention from "./entities/mention";
import type * as Notification from "./entities/notification";
import type * as PollOption from "./entities/poll_option";
import type * as Poll from "./entities/poll";
import type * as Preferences from "./entities/preferences";
import type * as PushSubscription from "./entities/push_subscription";
import type * as Relationship from "./entities/relationship";
import type * as Report from "./entities/report";
import type * as Results from "./entities/results";
import type * as Role from "./entities/role";
import type * as ScheduledStatus from "./entities/scheduled_status";
import type * as Source from "./entities/source";
import type * as Stats from "./entities/stats";
import type * as Status from "./entities/status";
import type * as StatusParams from "./entities/status_params";
import type * as StatusSource from "./entities/status_source";
import type * as Tag from "./entities/tag";
import type * as Token from "./entities/token";
import type * as URLs from "./entities/urls";

export namespace MastodonEntity {
	export type Account = Account.Account;
	export type Activity = Activity.Activity;
	export type Announcement = Announcement.Announcement;
	export type AnnouncementAccount = Announcement.AnnouncementAccount;
	export type AnnouncementReaction = Announcement.AnnouncementReaction;
	export type AnnouncementStatus = Announcement.AnnouncementStatus;
	export type Application = Application.Application;
	export type AsyncAttachment = AsyncAttachment.AsyncAttachment;
	export type Attachment = Attachment.Attachment;
	export type Focus = Attachment.Focus;
	export type Meta = Attachment.Meta;
	export type Sub = Attachment.Sub;
	export type Card = Card.Card;
	export type Context = Context.Context;
	export type Conversation = Conversation.Conversation;
	export type Emoji = Emoji.Emoji;
	export type FeaturedTag = FeaturedTag.FeaturedTag;
	export type Field = Field.Field;
	export type Filter = Filter.Filter;
	export type FilterContext = Filter.FilterContext;
	export type History = History.History;
	export type IdentityProof = IdentityProof.IdentityProof;
	export type Instance = Instance.Instance;
	export type List = List.List;
	export type Marker = Marker.Marker;
	export type Mention = Mention.Mention;
	export type Notification = Notification.Notification;
	export type NotificationType = Notification.NotificationType;
	export type PollOption = PollOption.PollOption;
	export type Poll = Poll.Poll;
	export type Preferences = Preferences.Preferences;
	export type PushSubscription = PushSubscription.PushSubscription;
	export type Alerts = PushSubscription.Alerts;
	export type Relationship = Relationship.Relationship;
	export type Report = Report.Report;
	export type Category = Report.Category;
	export type Results = Results.Results;
	export type Role = Role.Role;
	export type ScheduledStatus = ScheduledStatus.ScheduledStatus;
	export type Source = Source.Source;
	export type Stats = Stats.Stats;
	export type StatusParams = StatusParams.StatusParams;
	export type Status = Status.Status;
	export type StatusTag = Status.StatusTag;
	export type StatusSource = StatusSource.StatusSource;
	export type Tag = Tag.Tag;
	export type Token = Token.Token;
	export type URLs = URLs.URLs;
}

export default MastodonEntity;
