[workspace]
resolver = "2"
members = [
	"crates/*",
]

[workspace.package]
version = "4.16.0"
edition = "2024"
authors = ["esurio"]
license = "AGPL-3.0"
rust-version = "1.91.0"

[workspace.dependencies]
async-std = { version = "1", features = ["attributes", "tokio1"] }
clap = { version = "4.5.51", features = ["derive", "env"] }
chrono = "0.4.42"
tokio ={ version = "1.48.0", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
serde_yml = "0.0.12"
sea-orm = { version = "1.1.17", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros", "with-chrono", "with-json", "with-time", "seaography"] }
seaography = { version = "1.1.4", features = ["default"] }
thiserror = "2.0.17"
once_cell = "1.21.3"
toml = { version = "0.9.8", features = ["serde", "parse", "display"] }
tracing = "0.1.41"
log = "0.4.28"
dotenvy = "0.15.7"
regex = "1.12.2"
image = { version = "0.25.8", features = ["default-formats", "serde", "rayon", "nasm"] }
jxl-oxide = { version = "0.12.5", features = ["rayon", "image"] }
apalis = { version = "0.7.3", features = ["tracing", "retry", "timeout", "limit", "filter", "catch-panic", "prometheus"] }
apalis-redis = { version = "0.7.3", features = ["tokio-comp"] }
axum = { version = "0.8.6", features = ["form", "http1", "http2", "json", "macros" ,"matched-path", "multipart", "original-uri", "query", "tokio", "tower-log", "tracing", "ws"] }
rayon = "1.11.0"
