packages:
  - packages/backend
  - packages/frontend-shared
  - packages/frontend
  - packages/frontend-builder
  - packages/frontend-embed
  - packages/icons-subsetter
  - packages/sw
  - packages/cherrypick-js
  - packages/cherrypick-js/generator
  - packages-internal/label-manager
  - packages-internal/changelog-checker
onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@sentry/profiling-node'
  - '@sentry/node-cpu-profiler'
  - '@swc/core'
  - '@tensorflow/tfjs-node'
  - argon2
  - bufferutil
  - canvas
  - core-js
  - esbuild
  - msgpackr-extract
  - msw
  - nice-napi
  - protobufjs
  - re2
  - sharp
  - utf-8-validate
  - v-code-diff
  - vue-demi
ignorePatchFailures: false
overrides:
  chokidar: 4.0.3
  lodash: 4.18.1
  '@aiscript-dev/aiscript-languageserver': '-'
  # 脆弱性対応: 依存元が古いバージョンを固定しているため上書き
  '@misskey-dev/summaly>fastify': 5.12.1
  'undici@^7': 7.29.0
  'protobufjs@^7': 7.6.6
minimumReleaseAge: 10080 # delay 7days to mitigate supply-chain attack
minimumReleaseAgeExclude:
  - happy-dom # セキュリティ修正のため一時的に。そのうち消すこと
  - rolldown # 脆弱性対応。そのうち消す
  - '@rolldown/*' # 脆弱性対応。そのうち消す
  - vite # 脆弱性対応。そのうち消す
  - '@oxc-project/types'
