//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "chat_message")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(column_name = "fromUserId")]
    pub from_user_id: String,
    #[sea_orm(column_name = "toUserId")]
    pub to_user_id: Option<String>,
    #[sea_orm(column_name = "toRoomId")]
    pub to_room_id: Option<String>,
    pub text: Option<String>,
    pub uri: Option<String>,
    pub reads: Vec<String>,
    #[sea_orm(column_name = "fileId")]
    pub file_id: Option<String>,
    pub reactions: Vec<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::chat_room::Entity",
        from = "Column::ToRoomId",
        to = "super::chat_room::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ChatRoom,
    #[sea_orm(
        belongs_to = "super::drive_file::Entity",
        from = "Column::FileId",
        to = "super::drive_file::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    DriveFile,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::ToUserId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    User2,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::FromUserId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    User1,
}

impl Related<super::chat_room::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatRoom.def()
    }
}

impl Related<super::drive_file::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DriveFile.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::chat_room::Entity")]
    ChatRoom,
    #[sea_orm(entity = "super::drive_file::Entity")]
    DriveFile,
    #[sea_orm(entity = "super::user::Entity", def = "Relation::User2.def()")]
    User2,
    #[sea_orm(entity = "super::user::Entity", def = "Relation::User1.def()")]
    User1,
}
