//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "chat_room")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    #[sea_orm(column_name = "ownerId")]
    pub owner_id: String,
    pub description: String,
    #[sea_orm(column_name = "isArchived")]
    pub is_archived: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::chat_message::Entity")]
    ChatMessage,
    #[sea_orm(has_many = "super::chat_room_invitation::Entity")]
    ChatRoomInvitation,
    #[sea_orm(has_many = "super::chat_room_membership::Entity")]
    ChatRoomMembership,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::OwnerId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::chat_message::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatMessage.def()
    }
}

impl Related<super::chat_room_invitation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatRoomInvitation.def()
    }
}

impl Related<super::chat_room_membership::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatRoomMembership.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::chat_message::Entity")]
    ChatMessage,
    #[sea_orm(entity = "super::chat_room_invitation::Entity")]
    ChatRoomInvitation,
    #[sea_orm(entity = "super::chat_room_membership::Entity")]
    ChatRoomMembership,
    #[sea_orm(entity = "super::user::Entity")]
    User,
}
