//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

pub mod prelude;

pub mod abuse_report_notification_recipient;
pub mod abuse_report_resolver;
pub mod abuse_user_report;
pub mod access_token;
pub mod ad;
pub mod announcement;
pub mod announcement_read;
pub mod antenna;
pub mod app;
pub mod auth_session;
pub mod avatar_decoration;
pub mod blocking;
pub mod bubble_game_record;
pub mod channel;
pub mod channel_favorite;
pub mod channel_following;
pub mod channel_note_pining;
pub mod chat_approval;
pub mod chat_message;
pub mod chat_room;
pub mod chat_room_invitation;
pub mod chat_room_membership;
pub mod clip;
pub mod clip_favorite;
pub mod clip_note;
pub mod drive_file;
pub mod drive_folder;
pub mod emoji;
pub mod event;
pub mod flash;
pub mod flash_like;
pub mod follow_request;
pub mod following;
pub mod gallery_like;
pub mod gallery_post;
pub mod hashtag;
pub mod instance;
pub mod messaging_message;
pub mod meta;
pub mod migrations;
pub mod moderation_log;
pub mod muting;
pub mod note;
pub mod note_draft;
pub mod note_favorite;
pub mod note_reaction;
pub mod note_schedule;
pub mod note_thread_muting;
pub mod note_unread;
pub mod note_watching;
pub mod page;
pub mod page_like;
pub mod password_reset_request;
pub mod poll;
pub mod poll_vote;
pub mod promo_note;
pub mod promo_read;
pub mod registration_ticket;
pub mod registry_item;
pub mod relay;
pub mod renote_muting;
pub mod retention_aggregation;
pub mod reversi_game;
pub mod reversi_matching;
pub mod role;
pub mod role_assignment;
pub mod sea_orm_active_enums;
pub mod signin;
pub mod sw_subscription;
pub mod system_account;
pub mod system_webhook;
pub mod used_username;
pub mod user;
pub mod user_group;
pub mod user_group_invitation;
pub mod user_group_invite;
pub mod user_group_joining;
pub mod user_ip;
pub mod user_keypair;
pub mod user_list;
pub mod user_list_favorite;
pub mod user_list_membership;
pub mod user_memo;
pub mod user_note_pining;
pub mod user_pending;
pub mod user_profile;
pub mod user_publickey;
pub mod user_security_key;
pub mod webhook;

seaography::register_entity_modules!([
    abuse_report_notification_recipient,
    abuse_report_resolver,
    abuse_user_report,
    access_token,
    ad,
    announcement,
    announcement_read,
    antenna,
    app,
    auth_session,
    avatar_decoration,
    blocking,
    bubble_game_record,
    channel,
    channel_favorite,
    channel_following,
    channel_note_pining,
    chat_approval,
    chat_message,
    chat_room,
    chat_room_invitation,
    chat_room_membership,
    clip,
    clip_favorite,
    clip_note,
    drive_file,
    drive_folder,
    emoji,
    event,
    flash,
    flash_like,
    follow_request,
    following,
    gallery_like,
    gallery_post,
    hashtag,
    instance,
    messaging_message,
    meta,
    migrations,
    moderation_log,
    muting,
    note,
    note_draft,
    note_favorite,
    note_reaction,
    note_schedule,
    note_thread_muting,
    note_unread,
    note_watching,
    page,
    page_like,
    password_reset_request,
    poll,
    poll_vote,
    promo_note,
    promo_read,
    registration_ticket,
    registry_item,
    relay,
    renote_muting,
    retention_aggregation,
    reversi_game,
    reversi_matching,
    role,
    role_assignment,
    signin,
    sw_subscription,
    system_account,
    system_webhook,
    used_username,
    user,
    user_group,
    user_group_invitation,
    user_group_invite,
    user_group_joining,
    user_ip,
    user_keypair,
    user_list,
    user_list_favorite,
    user_list_membership,
    user_memo,
    user_note_pining,
    user_pending,
    user_profile,
    user_publickey,
    user_security_key,
    webhook,
]);
seaography::register_active_enums!([
    sea_orm_active_enums::AbuseReportResolverExpiresatEnum,
    sea_orm_active_enums::AntennaSrcEnum,
    sea_orm_active_enums::EventNotevisibilityEnum,
    sea_orm_active_enums::InstanceSuspensionstateEnum,
    sea_orm_active_enums::NoteSearchableByEnum,
    sea_orm_active_enums::NoteVisibilityEnum,
    sea_orm_active_enums::PageVisibilityEnum,
    sea_orm_active_enums::PollNotevisibilityEnum,
    sea_orm_active_enums::RelayStatusEnum,
    sea_orm_active_enums::RoleTargetEnum,
    sea_orm_active_enums::UserProfileFollowersVisibilityEnum,
    sea_orm_active_enums::UserProfileFollowingvisibilityEnum,
]);
