//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "note_draft")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(column_name = "replyId")]
    pub reply_id: Option<String>,
    #[sea_orm(column_name = "renoteId")]
    pub renote_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub text: Option<String>,
    pub cw: Option<String>,
    #[sea_orm(column_name = "userId")]
    pub user_id: String,
    #[sea_orm(column_name = "localOnly")]
    pub local_only: Option<bool>,
    #[sea_orm(column_name = "reactionAcceptance")]
    pub reaction_acceptance: Option<String>,
    pub visibility: String,
    #[sea_orm(column_name = "fileIds")]
    pub file_ids: Option<Vec<String>>,
    #[sea_orm(column_name = "visibleUserIds")]
    pub visible_user_ids: Option<Vec<String>>,
    pub hashtag: Option<String>,
    #[sea_orm(column_name = "channelId")]
    pub channel_id: Option<String>,
    #[sea_orm(column_name = "hasPoll")]
    pub has_poll: Option<bool>,
    #[sea_orm(column_name = "pollChoices")]
    pub poll_choices: Option<Vec<String>>,
    #[sea_orm(column_name = "pollMultiple")]
    pub poll_multiple: Option<bool>,
    #[sea_orm(column_name = "pollExpiresAt")]
    pub poll_expires_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_name = "pollExpiredAfter")]
    pub poll_expired_after: Option<i64>,
    #[sea_orm(column_name = "hasEvent")]
    pub has_event: Option<bool>,
    #[sea_orm(column_name = "eventStart")]
    pub event_start: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_name = "eventEnd")]
    pub event_end: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_name = "eventTitle")]
    pub event_title: Option<String>,
    #[sea_orm(column_name = "eventMetadata", column_type = "JsonBinary", nullable)]
    pub event_metadata: Option<Json>,
    #[sea_orm(column_name = "disableRightClick")]
    pub disable_right_click: Option<bool>,
    #[sea_orm(column_name = "deleteAt")]
    pub delete_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::channel::Entity",
        from = "Column::ChannelId",
        to = "super::channel::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Channel,
    #[sea_orm(
        belongs_to = "super::note::Entity",
        from = "Column::RenoteId",
        to = "super::note::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Note2,
    #[sea_orm(
        belongs_to = "super::note::Entity",
        from = "Column::ReplyId",
        to = "super::note::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Note1,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::channel::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Channel.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::channel::Entity")]
    Channel,
    #[sea_orm(entity = "super::note::Entity", def = "Relation::Note2.def()")]
    Note2,
    #[sea_orm(entity = "super::note::Entity", def = "Relation::Note1.def()")]
    Note1,
    #[sea_orm(entity = "super::user::Entity")]
    User,
}
