services:
  c.test:
    extends:
      file: ./compose.tpl.yml
      service: nginx
    depends_on:
      cherrypick.c.test:
        condition: service_healthy
    networks:
      - internal_network_c
    volumes:
      - type: bind
        source: ./.config/c.test.conf
        target: /etc/nginx/conf.d/c.test.conf
        read_only: true
      - type: bind
        source: ./certificates/c.test.crt
        target: /etc/nginx/certificates/c.test.crt
        read_only: true
      - type: bind
        source: ./certificates/c.test.key
        target: /etc/nginx/certificates/c.test.key
        read_only: true

  cherrypick.c.test:
    extends:
      file: ./compose.tpl.yml
      service: cherrypick
    depends_on:
      db.test:
        condition: service_healthy
      redis.test:
        condition: service_healthy
    networks:
      - internal_network_c
    volumes:
      - type: bind
        source: ./.config/c.test.default.yml
        target: /cherrypick/.config/default.yml
        read_only: true

networks:
  internal_network_c:
    internal: true
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/16
          ip_range: 172.24.0.0/24
