[package]
name = "notectl"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = { workspace = true, features = ["derive"]}
clap_derive = { workspace = true}
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
vapid = { workspace = true }

rs-shared ={ path = "../rs-shared" }
